### ISSUE TITLE
[feauture request] Provide latest release status metric

### ISSUE THREAD

**Issue by sotzdra** [webdevops/azure-devops-exporter#11]
I think, a metric similar to azure_devops_build_latest_status would be also useful for releases.

In this way someone would be able to see the status of the last release for every Release definition and figure out if a release is failing or not.

**Comment by mblaschke** [comment]
There is a `azure_devops_release_info`, `azure_devops_release_environment` and a `azure_devops_release_environment_status`.

Each release can have multiple relases with different environments and every environment can have a different release. So it's quite difficult to get the desired informations.

Which informations do you want?

**Comment by sotzdra** [comment]
We want to build a grafana dashboard woth a table panel, where we want to show only the failed releases for whom there is no newer successful release.
For example, if we say Release Definition has three stages dev - int - prod and there is:
Release-1 with failed deployment to dev and 
Release-2 with successful deployment to dev - int - prod and 
Release-3 with successful deployment to dev but failed in int 

The Grafana dashboard show a table as following:
Definition name status stage
Release-3 failed int
Release-3 success dev 
Release-2 success prod

The intention behind this dashboard is to have an immediate information on what is failing and what is the last successful deployment.

**Comment by mblaschke** [comment]
Added an example promql query to README for releases.
Please also try `0.8.0-beta11`
