### ISSUE TITLE
[feauture request] monitoring free minutes in public ado agents

### ISSUE THREAD

**Issue by piostelmach** [webdevops/azure-devops-exporter#12]
I don't see metric from pipelines->parallel jobs. It will be very usefull who want monitoring free public minutes in own projects :)

![image](https://user-images.githubusercontent.com/28858287/64432304-8bd60980-d0bc-11e9-8cf8-d59798a92281.png)

**Comment by mblaschke** [comment]
Is a48ecc16c8dcc25d32762ea470ac854d8ded5749 fixing this?
See azure_devops_resourceusage_build in `0.8.0-beta9`

**Comment by piostelmach** [comment]
@mblaschke I've checked and this metrics "azure_devops_resourceusage_build" not show currently consumed minutes :/

output from azure_devops_resourceusage_build:
![image](https://user-images.githubusercontent.com/28858287/64512677-3467b180-d2e7-11e9-8c5d-1443ad491f9c.png)

and output form azure devops portal:
![image](https://user-images.githubusercontent.com/28858287/64512786-65e07d00-d2e7-11e9-9cc4-155541eccc1c.png)

**Comment by piostelmach** [comment]
and valid url for this view "/_settings/buildqueue?_a=concurrentJobs"

**Comment by mblaschke** [comment]
Hm.. i don't find a REST api to query these informations.
There is only the Build ResourceUsage REST api: https://docs.microsoft.com/en-us/rest/api/azure/devops/build/resource%20usage/get?view=azure-devops-rest-5.1

**Comment by mblaschke** [comment]
still no api, asking Azure DevOps via Twitter :)

**Comment by mblaschke** [comment]
https://twitter.com/AzureDevOps/status/1206564769009983488 🎉

**Comment by mblaschke** [comment]
Will be included in next version

**Comment by mblaschke** [comment]
Will be included in final 0.8.0 release
