### ISSUE TITLE
Prometheus exporter for Azure DevOps Server

### ISSUE THREAD

**Issue by juanperezADD** [webdevops/azure-devops-exporter#13]
Any plan to support it for Azure DevOps Server?

We are interested in getting statistics of build times (elapsed and queue wait time), agent pool utilization,... but in Azure DevOps Server 2019.

If it is not possible, is there any other alternative?

Thank you in advance

**Comment by nicksterx** [comment]
It is possible. You need to configure the AZURE_DEVOPS_URL value to point to your Azure Devops Server.

**Comment by juanperezADD** [comment]
Thanks for your answer

I tried to install it on a Windows machine as a Docker container but I couldn't. 

When I build the image using the dockerfile the following error appears:
`The token '&&' is not a valid statement separator in this version.`

I changed the "Compile" step of the dockerfile:
COPY ./ /go/src/github.com/webdevops/azure-devops-exporter
ENV CGO_ENABLED 0
ENV GOOS windows
RUN go build -a -ldflags '-extldflags "-static"' -o /azure-devops-exporter
RUN chmod +x /azure-devops-exporter
RUN /azure-devops-exporter --help

When I build the image again the following error appears:
`go: inconsistent vendoring in c:\go\src\github.com\webdevops\azure-devops-exporter
go.mod requires github.com/webdevops/azure-devops-exporter but vendor/modules.txt does not include it.
run 'go mod tidy; go mod vendor' to sync'`

Is there any image available for Windows? Once I install it, how can I use it? In the documentation it is used as a console application. Would I have to connect to the container to use it?

I'm sorry for so many questions but I don't understand how to install and use it. I have no knowledge in the Go language.

Thank you in advance

**Comment by mblaschke** [comment]
You can run the Docker image with Docker for windows (using Linux containers). In the background there is a Linux kernel running which runs the container, no need to switch `GOOS`.

If you want to run it inside Windows containers (Docker for Windows with Windows containers) that's a different story. There you have to switch to a windowsserver image in the final image but i never tested this. In theory this should also work.

**Comment by mblaschke** [comment]
if still needed, please reopen this issue.
