### ISSUE TITLE
azure_devops_stats_project_builds_duration has a value of NaN

### ISSUE THREAD

**Issue by chelnak** [webdevops/azure-devops-exporter#14]
It appears that the value for `azure_devops_stats_project_builds_duration` is NaN.

![image](https://user-images.githubusercontent.com/3777574/65839658-54e3c400-e307-11e9-9528-aa1f16daf21f.png)

Had a quick look through the [stats exporter](https://github.com/webdevops/azure-devops-exporter/blob/a03921c2609dee5f6bdb44eb917fa650ae14c42a/metrics_stats.go#L159) and couldn't really see what was going on. 

Any ideas?

**Comment by mblaschke** [comment]
How often do you scrape?

**Comment by chelnak** [comment]
Fairly frequently. Every few minutes.

**Comment by chelnak** [comment]
@mblaschke Did you have any additional thoughts about this?

**Comment by mblaschke** [comment]
Any errors in the logs? Are you using `dev.azure.com`?

Will check this in the next days.

**Comment by chelnak** [comment]
No errors and yes using dev.azure.com

Cheers

**Comment by mblaschke** [comment]
Will refactor the exporter in the next days/weeks. currently not happy and I also want to summarize the values better

**Comment by mblaschke** [comment]
Should be already fixed, please try with `0.8.0-beta11`
