### ISSUE TITLE
Number of Jobs in queue (waiting for free agents) in Agent Pool

### ISSUE THREAD

**Issue by AlbMor** [webdevops/azure-devops-exporter#17]
Hi

We started to use this Azure DevOps exporter and it is working really well.

We need to have the information on how many jobs are in queue in real time (waiting for a free Agent) per Agent Pool.

We looked to get it but we did not find a way also combining different others metrics

Is it possible to get this metric?

Could you help us on that?

Thanks

Alberto

**Comment by mblaschke** [comment]
Hm.. is there an rest api for that?
There are a lot of APIs which Azure DevOps uses but they are closed and not documented :(

**Comment by AlbMor** [comment]
Hi 

I am not aware of such Rest API

Maybe we can extrapolate the number of waiting  for Agent with a formula

Number of jobs Wating for Agent in a Pool= Number of Jobs requests in the Pool - Number of Agents in the Pool

So We just need

Number of Jobs requests in the Pool 

and 

Number of Agents in the Pool

Do we have such a metrics now?

I think Number of Agents in the Pool is the `azure_devops_agentpool_size`

but do we have Number of Jobs requests in the Pool  metric?

Please let me know if you have some ideas

Thanks

**Comment by AlbMor** [comment]
Hi Again,

I found this Rest API

https://{organization}.visualstudio.com/_apis/distributedtask/pools/{poolid}/jobrequests

is returning the jobrequests for specific pool in JSON format

In the JSON result, each build have some properties, if the build started to run on an agent it gets a property `assignTime`, so If we don´t have this property it means the job is waiting

We can count how many of those jobs without the property `assignTime` are present for a specific pool

What do you think?

Please let me know if it is feasable

Thanks

Alberto

**Comment by ScottGuymer** [comment]
@AlbMor I ran into the same need so I had a little go at adding this in #18 

Reviews would be very much appreciated.

**Comment by AlbMor** [comment]
We have now a metric doing that
azure_devops_agentpool_queue_length
Thanks

**Comment by ruskinb1** [comment]
Hi.. Could You please help how we can use this Metric in Real time.. This exactly matchi our use Case

**Comment by ruskinb1** [comment]
Could anyone please help on that, How we can setup prometheus for only this use case.
