### ISSUE TITLE
Missing azure_devops_agentpool_agent metrics

### ISSUE THREAD

**Issue by johi12** [webdevops/azure-devops-exporter#21]
Hi,

I seem to be missing the following metrics, 

azure_devops_agentpool_agent_status
azure_devops_agentpool_agent_job
azure_devops_agentpool_agent_info

I'm using the following flags when starting the exporter
      - "--verbose"
      - "--bind=:9393"
      - "--azuredevops.access-token=xxxxx"
      - "--azuredevops.organisation=xxxxx"
      - "--blacklist.project=xxxxx"

I've set the PAT to have full access. 

I'm using versio 0.8.4

Thanks

**Comment by sco-pi** [comment]
Hey @johi12, I run into the same problem. Just been tracing my way through the code to find the cause and I've tracked something down.

By default it appears that azure-devops-exporter won't pickup any/ all of the agent pools and it needs to have them specifically enabled for monitoring, you can do that by running with the `--whitelist.agentpool` option or with the `AZURE_DEVOPS_FILTER_AGENTPOOL` env var (I wasn't able to get the syntax right for the cli option, but the env var is a space separated list).

Hope that helps!

**Comment by mblaschke** [comment]
please reopen if not solved
