### ISSUE TITLE
issue setting up exporter

### ISSUE THREAD

**Issue by Ankitchandre** [webdevops/azure-devops-exporter#23]
I am trying to run this image as a kuberenetes deployment on my local K8. We have a azure server running on other machine . I provided azure environment variables like AZURE_DEVOPS_URL, AZURE_DEVOPS_ORGANISATION and AZURE_DEVOPS_ACCESS_TOKEN, but still getting the following error : 

the required flags `--azuredevops.access-token' and `--azuredevops.organisation' were not specified

Can someone provide us info on how we can setup this up . 
Note: Prometheus is also running on my local k8.

**Comment by mblaschke** [comment]
Which version are you using?
How do you run it? Can you share the definition (without secrets)?

**Comment by Ankitchandre** [comment]
by version you meant kuberenetes version ?
kubernetes version >  v1.16.5
simple deployment > 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: azureexporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azureexporter
  template:
    metadata:
      labels:
        app: azureexporter
    spec:
      containers:
      - name: azureexporter
        image: azureexporter
        imagePullPolicy: Never
        env:
          - name: AZURE_DEVOPS_URL
            value: "myurl"
          - name: AZURE_DEVOPS_ORGANISATION
            value: "myorg"

AZURE_DEVOPS_ACCESS_TOKEN is taken from secrets. The image mentioned in this deployment is the dockerfile build done from master branch.

**Comment by mblaschke** [comment]
Do  you use the official Azure Devops (cloud instance) on https://dev.azure.com? Then you don't need the URL, only the org.

Are you sure that `AZURE_DEVOPS_ACCESS_TOKEN` is supplied via the secret and is not empty?

**Comment by Ankitchandre** [comment]
No , we are using on prem version not cloud . 
cross checked secret is not empty. I tried using AZURE_DEVOPS_ACCESS_TOKEN  as ENV also , same result.

**Comment by mblaschke** [comment]
do you still have problems?
