### ISSUE TITLE
how to store metrics to external prometheus database

### ISSUE THREAD

**Issue by tsaibabu4u** [webdevops/azure-devops-exporter#29]
Hi There,
I was able to run the docker image and able to see the collected metrics information but I dont see any prometheus url to query ?
is it possible to push these metrics to my own prometheus databse ?

**Comment by mblaschke** [comment]
metrics are available via `/metrics` endpoint.

**Comment by tsaibabu4u** [comment]
Thank you for the response. I don't see any service running on any port while running this docker image in local
will it generate any endpoint ? if so what would be the url

CONTAINER ID   IMAGE                             COMMAND                  CREATED        STATUS        PORTS                    NAMES
478b2e3f8d5a   webdevops/azure-devops-exporter   "/azure-devops-expor…"   4 hours ago    Up 4 hours                             awesome_hugle

**Comment by Sreekanth-BM** [comment]
@tsaibabu4u  : Did you find a way to get metrics to any endpoint? (http://localhost:9090)

**Comment by mblaschke** [comment]
Use the container IP or hostname and fetch it directly from the container (recommended) or map the port to the host.
