### ISSUE TITLE
rate limit issue

### ISSUE THREAD

**Issue by tsaibabu4u** [webdevops/azure-devops-exporter#30]
Hi There,
When I run with default settings I got rate limit exceeded issue in my production environment. 
How specific time values we need to change to avoid this issue?
If I want to poll every day only once what parameter should I use and value?

**Comment by mblaschke** [comment]
Try to reduce scrape times and reduce `request.concurrency` (numbers of requests in parellel).


eg:
SCRAPE_TIME_LIVE=1m
SCRAPE_TIME=6h
REQUEST_CONCURRENCY=2

**Comment by tsaibabu4u** [comment]
Thank you
