### ISSUE TITLE
unsupported protocol scheme collect releases

### ISSUE THREAD

**Issue by alejog38** [webdevops/azure-devops-exporter#31]
I have a problem with the scrapping only with collect releases because another collects works fine

this is the error.

![1](https://user-images.githubusercontent.com/15347097/106941843-6a35e300-66f1-11eb-8583-e84ab98d3234.PNG)
![2](https://user-images.githubusercontent.com/15347097/106941844-6b671000-66f1-11eb-913e-7a573f5c5d73.PNG)

Thanks for your help.

**Comment by mblaschke** [comment]
With which options are your running this exporter?
Which version?

**Comment by alejog38** [comment]
Im using the 20.11.0 version, and i detect that the url azure devops API for releases list change with respect another API, because i use the http://dev.azure.com url to get list from agent pool but for releases list use https://vsrm.dev.azure.com/ url 

I dont if i need change something in the params.

**Comment by stobias123** [comment]
seeing the same.

**Comment by stobias123** [comment]
I took some time looking into this more, looks like some extra URL escaping is happening. I'm building off master.

**Comment by alejog38** [comment]
Thanks for your help, works perfect
