### ISSUE TITLE
Unable to see lot of metrics after adding the exporter

### ISSUE THREAD

**Issue by sasemb** [webdevops/azure-devops-exporter#40]
Hi ,

Recently I'm trying to build a dashboard in grafana for each project we have in one organization and building release pipeline deployment status and current release definition details into it . I deployed the exporter as docker instance and integrated with prometheus . Able to see other metrics such as agent build , build info etc but the below metrics are not present when i try to query it . please help me in fixing this

azure_devops_release_info | release | Release informations
-- | -- | --
azure_devops_release_artifact | release | Release artifcact informations
azure_devops_release_environment | release | Release environment list
azure_devops_release_environment_status | release | Release environment status informations
azure_devops_release_approval | release | Release environment approval list
azure_devops_release_definition_info | release | Release definition info
azure_devops_release_definition_environment | release | Release definition environment list

None of the release metrics are available in UI and in metric log as well

**Comment by sasemb** [comment]
Also when I inspect the logs , I'm seeing this 404 error message while fetching the metrics . I tried with latest api version 6.0 as well but looks someissue with the back end code

Please refer the attachment

![image](https://user-images.githubusercontent.com/31820752/121804356-90512e00-cc63-11eb-96cc-3ce84c9ed4d0.png)

**Comment by sasemb** [comment]
Also please guide me how i can pass multiple project uuid to AZURE_DEVOPS_FILTER_PROJECT

I tried by giving comma seperated and also passed two arguements seperately . none of them worked

**Comment by sasemb** [comment]
@mblaschke  please give your insights . thanks

**Comment by mblaschke** [comment]
Please use spaces to separate UUIDs

Does the PAT token have the permissions to fetch these information? The exporter can only fetch information when it's allowed via permission system.

**Comment by mblaschke** [comment]
closed, missing feedback
please reopen if issue still exists
