### ISSUE TITLE
How to restrict the program to specific metric while we pull from AZ devops 

### ISSUE THREAD

**Issue by dineshpsalm** [webdevops/azure-devops-exporter#44]
Hi Team, 

First a fall, thanks a million for creating such a useful repo and sharing same with our people. Here, I like to know how can I restrict the metric which I pull from azure devops. Currently, we are getting a lot of irrelevant data and we are very sure in a long run this will cause a issue in storage part. Hence, from the beginning, we like to be more cautious about what the data we are going to pull to save space in HD. Pls let me know your comments. 

Pls give step by step assistance. If possible, add screenshot or document. So that, people whoever like me get benefit. 

Currently, I converted this repo into exe file using go build 
Environment - WIndows

**Comment by mblaschke** [comment]
please let me know if you have more question and feel free to reopen the issue
