### ISSUE TITLE
ADO Build metrics granularity

### ISSUE THREAD

**Issue by pge-bw** [webdevops/azure-devops-exporter#46]
Hi,
What do you think about increasing granularity level for build metrics? 
I mean add additional metrics for stage/job/tasks objects in ADO.
From this api:
https://docs.microsoft.com/en-us/rest/api/azure/devops/build/timeline/get?view=azure-devops-rest-6.1

**Comment by fcorange** [comment]
+1 This will be very useful. Is this something planned for the project?

**Comment by mblaschke** [comment]
thinking already about it, but will take some time.

the goal is to create more summarised metrics

**Comment by pge-bw** [comment]
Created PR for new build metrics. @mblaschke, could you please take a look:
https://github.com/webdevops/azure-devops-exporter/pull/49
