### ISSUE TITLE
Number of failed builds

### ISSUE THREAD

**Issue by steinhobelgruen** [webdevops/azure-devops-exporter#5]
Wouldn't it be a good idea to add something like the number of consecutive build results (successful/failed/cancelled) to the latest status for a build definition?

**Comment by mblaschke** [comment]
The new statistics collector is now collecting the number of failed builds per project, definition and agentpool. At least something to monitor.

**Comment by mblaschke** [comment]
Please try the promql query in README for getting the last release.
Also `azure_devops_stats_project_release_duration` could be used as it also has the status of each release.
