### ISSUE TITLE
Access tokens expiration metrics

### ISSUE THREAD

**Issue by gillg** [webdevops/azure-devops-exporter#52]
Hello,

Because this exporter will probably run on a "technical account" it will be not always obvious to keep attention on azure DevOps email or being in a mailing list.
So a metrics to expose at least the current user  (the technical account used for metrics collect) access tokens expiration date would be super useful.

**Comment by mblaschke** [comment]
only works with an AzureAD access token (not with a PAT):
https://docs.microsoft.com/en-us/rest/api/azure/devops/tokens/?view=azure-devops-rest-7.1&tabs=powershell

**Comment by mblaschke** [comment]
Cannot be solved by exporter using PAT
