### ISSUE TITLE
Missing metrics (and incorrect agentPoolId)

### ISSUE THREAD

**Issue by worldspawn** [webdevops/azure-devops-exporter#53]
I don't seem to be getting the azure_devops_agentpool_queue_length metric.

I only see these metrics
![image](https://user-images.githubusercontent.com/819581/145186971-fbcecbbc-208e-47fa-a517-e9a4e26f00aa.png)

I can't see any errors in the exporters logs. Is there any guidance on what permissions to enable for the PAT?

**Comment by worldspawn** [comment]
Also `azure_devops_build_latest_info` seems to be reporting the wrong agentPoolId. Heres a build 
```
azure_devops_build_latest_info{agentPoolID="13", buildDefinitionID="112", buildID="30597", buildName="Integration Services - Apple App Store", buildNumber="20211208.4", container="azureexporter", endpoint="scrape", instance="10.244.2.4:8080", job="devops-exporter", namespace="pipelines-agents", pod="devops-exporter-69697f4fd5-pfsj9", projectID="redacted", reason="manual", requestedBy="Sam Critchley", result="failed", service="devops-exporter", sourceBranch="refs/heads/develop", sourceVersion="c900631fb8baf641f9a110f2b628142c1036318b", status="completed", url="redacted"}
```

It says agentPoolID is 13. A quick scan of the agent_pool_info metric...
```
azure_devops_agentpool_info{agentPoolID="13", agentPoolName="Azure Pipelines", agentPoolType="automation", container="azureexporter", endpoint="scrape", instance="10.244.1.14:8080", isHosted="true", job="devops-exporter", namespace="pipelines-agents", pod="devops-exporter-5bbc64b555-j8g7w", service="devops-exporter"}
azure_devops_agentpool_info{agentPoolID="13", agentPoolName="Azure Pipelines", agentPoolType="automation", container="azureexporter", endpoint="scrape", instance="10.244.2.4:8080", isHosted="true", job="devops-exporter", namespace="pipelines-agents", pod="devops-exporter-69697f4fd5-pfsj9", service="devops-exporter"}
```

So 13 is "Azure Pipelines". The build number was `20211208.4`. 

That build ran in the Ubuntu Self Hosted pool (id - 15).

![image](https://user-images.githubusercontent.com/819581/145190001-b7890d2f-e842-4546-8448-206577169b6e.png)

Theres more occurrences of this where the pool id should have been 15 but is different values (not just 13).

**Comment by worldspawn** [comment]
I see my first problem is because I haven't set AZURE_DEVOPS_AGENTPOOL

**Comment by mblaschke** [comment]
thanks for the analysis, thinking about how to solve that and avoid additional api calls 🤔

**Comment by mblaschke** [comment]
> and that's how (theres possible a shorter route) you get the agent pool id for the build. My builds only use one pool, I don't know if its possible to have different stages/jobs use different pools.

every job block can have an own pool (eg. separating windows and linux jobs)


can you check the result for ``https://dev.azure.com/{TENANT}/{PROJECT}/_apis/build/builds?api-version=5.1&maxBuildsPerDefinition=1&deletedFilter=excludeDeleted``? what is inside the job block?


here is get (for a public testing instance):
```
{
  "id": 8,
  "name": "Hosted Ubuntu 1604",
  "pool": {
    "id": 8,
    "name": "Hosted Ubuntu 1604",
    "isHosted": true
  }
}
```

**Comment by nikhil-neu** [comment]
@worldspawn ...i have the same issue with the missing metrics , do we need to create AZURE_DEVOPS_AGENTPOOL during container creation ?
i was under the impression that this was just a filtering requirement.
If so , do i give the pool id's comma separated

**Comment by mblaschke** [comment]
yes you have to set the agentpool which you want to scrape.. the next version will fetch the metrics for all agentpool (even hosted ones) so you would not have to set the env var

**Comment by a1exstr** [comment]
> the next version will fetch the metrics for all agentpool (even hosted ones) so you would not have to set the env var

I would probably prefer having a list of pools or all pools if not defined rather than single pool vs all

**Comment by mblaschke** [comment]
you can set `AZURE_DEVOPS_AGENTPOOL="1 21 42` to set multiple pools (separated by space)

the next version will use all if not set.

**Comment by Crulex** [comment]
> you can set `AZURE_DEVOPS_AGENTPOOL="1 21 42` to set multiple pools (separated by space)
> 
> the next version will use all if not set.

Hi, is it possible that you will update this? Or we will need to put all pools id?

**Comment by mblaschke** [comment]
`22.7.0` released
