### ISSUE TITLE
Create a new environment to support the initial date to get the history

### ISSUE THREAD

**Issue by seilorjunior** [webdevops/azure-devops-exporter#55]
It is very good, if you have an environment that we can set how long the exporter should look back.

Example: I need to get the history of commits from all repos, but today I can't do that. 

Could you add that?

**Comment by mblaschke** [comment]
This exporter is actually not a reporting tool as it exports live data to a time series database (prometheus format).

Maybe it's better to create an own reporting tool but keep in mind that commits are not a valid KPI :)
