### ISSUE TITLE
About Duplicate Data

### ISSUE THREAD

**Issue by YandingZ** [webdevops/azure-devops-exporter#59]
Hi,

I am using your exporter and it is very powerful. It can grab a lot of information. But I have a couple of issues that are still unresolved. The first is that every time I use exporter. It always crawls a lot of duplicate data. The duplicate data appears once every 15 seconds. I don't really understand why this is happening. Would you please explain it ?

Thanks

**Comment by mblaschke** [comment]
Where do you see duplicate data? On the `/metrics` endpoint?

**Comment by YandingZ** [comment]
Thanks for reply! 

When I select a specific dashboard inside Grafana and convert it to table form, I see that there is a row of data every 15 seconds and then the data is basically duplicated. I would like to ask if this is normal?

Also, The default capture time in the yml file in Prometheus is 15 seconds, I tried to change the parameters but the result is still 15 seconds. So would you know any way we can change this capture time? For example, by changing the export code?
Thanks.

**Comment by mblaschke** [comment]
In Data source ensure that you have enabled the `Instant` flag or you will get all the metrics data in the date range you selected.

**Comment by mblaschke** [comment]
please reopen if this topic is not solved
