### ISSUE TITLE
unsupported protocol scheme

### ISSUE THREAD

**Issue by Drewster727** [webdevops/azure-devops-exporter#7]
v0.7.2 via docker

```
docker run --rm -e SERVER_BIND=":8180" -e AZURE_DEVOPS_ACCESS_TOKEN="<token>" -e AZURE_DEVOPS_URL="http://<tfs2018_host>:8080/tfs" -e AZURE_DEVOPS_ORGANISATION="somedomain.com" webdevops/azure-devops-exporter:latest
```

Seeing the following error. We do not have https turned on, this is an internal only box. Maybe someday we will... but for now, can we support this?

```
RESTY 2019/04/14 23:03:22 WARNING - Using Basic Auth in HTTP mode is not secure.
RESTY 2019/04/14 23:03:22 ERROR Get //%2Fcf50689a-3dca-47b7-9e2c-69371f767be6%2F_apis%2Fbuild%2Fbuilds%3Fapi-version=4.1&minTime=2019-04-14T23%253A02%253A52Z/cf50689a-3dca-47b7-9e2c-69371f767be6/_apis/build/builds?api-version=4.1&minTime=2019-04-14T23%3A02%3A52Z: unsupported protocol scheme "", Attempt 1
RESTY 2019/04/14 23:03:22 WARNING - Using Basic Auth in HTTP mode is not secure.
RESTY 2019/04/14 23:03:22 ERROR Get //%2Fcf50689a-3dca-47b7-9e2c-69371f767be6%2F_apis%2Fbuild%2Fbuilds%3Fapi-version=4.1&minTime=2019-04-14T23%253A02%253A52Z/cf50689a-3dca-47b7-9e2c-69371f767be6/_apis/build/builds?api-version=4.1&minTime=2019-04-14T23%3A02%3A52Z: unsupported protocol scheme "", Attempt 2
RESTY 2019/04/14 23:03:22 WARNING - Using Basic Auth in HTTP mode is not secure.
RESTY 2019/04/14 23:03:22 ERROR Get //%2Fcf50689a-3dca-47b7-9e2c-69371f767be6%2F_apis%2Fbuild%2Fbuilds%3Fapi-version=4.1&minTime=2019-04-14T23%253A02%253A52Z/cf50689a-3dca-47b7-9e2c-69371f767be6/_apis/build/builds?api-version=4.1&minTime=2019-04-14T23%3A02%3A52Z: unsupported protocol scheme "", Attempt 3
```

This spams the logs over and over again. Turning on verbose logging doesn't seem to yield any additional details.

Thanks,
Drew

**Comment by Drewster727** [comment]
I have found this may be an issue with my server being TFS 2018 vs azure devops (they are the same thing, except mine is on-prem and slightly different request format).
This is an example of a successful GET on git repos that seems to work with my setup:
```http://<server>:8080/tfs/DefaultCollection/_apis/git/repositories?api-version=2.0```

So, two things I'm hoping can be implemented:
- ability to specify the api version (this is attached to every call)
- ensure that if a HOST_URL is set, make sure all subsequent requests contain it, i.e. `<host_url>/_apis/....`

That make sense? I think it would finally get most/all of our on-prem TFS issues resolve.

Thanks!

**Comment by mblaschke** [comment]
Is it working with the new version?

**Comment by mblaschke** [comment]
Try either 0.8.0-beta1 or 0.8.0-beta2 (new api urls)

**Comment by mblaschke** [comment]
no feedback, closing
